export {default as Loader} from './Loader';
export {default as Navbar} from './Navbar';
export {default as Welcome} from './Welcome';
export {default as Vote} from './Vote';
export {default as Footer} from './Footer';
export {default as Candidate} from './Candidate';
export {default as Result} from './Result';
export {default as Connect} from './Connect';
export {default as Admin} from './Admin'; 